parameters:
    buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{ paramters.buildConfiguration }}'
  inputs:
    command: 'build'
    argments: '--no-restore --configuration ${{ paramters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ paramters.buildConfiguration }}'
  inputs:
    command: 'Publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    argments: '--no-build --configuration ${{ paramters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    zipAfterPublish: true